source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Mobilette/Specs.git'
platform :ios, '9.0'
use_frameworks!

target "MBRouterProtocol" do

    pod 'Alamofire'
    pod 'MobiletteFoundation'

end
